/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "LCD.h"
#include "KEYPAD.h"
#include "AFIO_Interface.h"
#include "EXTI_Interface.h"


char IRQ=0;

void EXTIB9_CALLBACK(void){

	LCD_WRITE_STRING("HI");
	delay_ms(1000);
	IRQ=1;
}

int main(void)
{

		GPIOA_CLK_ENABLE();
		GPIOB_CLK_ENABLE();
		AFIO_CLK_ENABLE();
		LCD_INIT();
		LCD_clear_screen();
		 void (*MPF)(void) = &EXTIB9_CALLBACK;
		EXTI_INIT(IOB, PIN9, EXTI_TRIGGER_RISING,MPF);
		while(1){
			if(IRQ){
				LCD_clear_screen();
				IRQ=0;
			}
		}
	}

