/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile int vuint32_t;

#define RCC_BASE 		 (0x40021000)
#define RCC_CR 			*(vuint32_t*)(RCC_BASE)
#define RCC_APB2ENR		*(vuint32_t*)(RCC_BASE + 0x18)

#define GPIOA_BASE   	 (0x40010800)
#define GPIOA_CRL		*(vuint32_t*)(GPIOA_BASE)
#define GPIOA_CRH		*(vuint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_IDR		*(vuint32_t*)(GPIOA_BASE + 0x08)

#define GPIOB_BASE 		 (0x40010C00)
#define GPIOB_CRL		*(vuint32_t*)(GPIOB_BASE)
#define GPIOB_CRH		*(vuint32_t*)(GPIOB_BASE + 0x04)
#define GPIOB_ODR		*(vuint32_t*)(GPIOB_BASE + 0x0C)

void init_clock();
void init_GPIOx();

int main(void)
{
	init_clock();
	init_GPIOx();
    /* Loop forever */
	while(1){

		if(!(GPIOA_IDR & 0x02)){

			GPIOB_ODR |= 0x02;

		}
		else{

			GPIOB_ODR &= ~0x02;
		}

		if(GPIOA_IDR & (1<<13)){

			GPIOB_ODR &= ~1<<13;

		}

		else{

			GPIOB_ODR |= 1<<13;

		}
	}
}

void init_clock(){	
	RCC_APB2ENR	|=	3<<2;
}
void init_GPIOx(){
	GPIOA_CRL	=	0;
	GPIOB_CRL	=	0;

	GPIOA_CRL	|=	(0x00<<4)|(1<<6);
	GPIOB_CRL	|=	(2<<4)|(1<<6);

	GPIOA_CRH	=	0;
	GPIOB_CRH	=	0;

	GPIOA_CRH	|=	(0x00<<20)|(1<<22);
	GPIOB_CRH	|=	(2<<20)|(1<<22);
}
